FROM node:24-slim

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY prisma ./prisma/
RUN npm init -y && npm install prisma@5.22.0 --save-exact

CMD ["npx", "prisma", "migrate", "deploy"]
